name: Build and Push - Frontend EciBombit

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: write
  actions: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Build for production (Nginx)
        run: npm run build

      - name: Login to Azure Container Registry
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push Docker image (Nginx)
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/front-client:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/front-client:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container App
        uses: azure/cli@v1
        with:
          azcliversion: "2.72.0"
          inlineScript: |
            az containerapp update \
              --name front-client \
              --resource-group BOMBIT-RG \
              --image ${{ secrets.ACR_NAME }}.azurecr.io/front-client:latest \
              --registry-identity "system" \
              --set-env-vars FRONTEND_URL=${{ secrets.FRONTEND_URL }} BACKEND_URL=${{ secrets.BACKEND_URL }} WEBSOCKET_URL=${{ secrets.WEBSOCKET_URL }}

#  sonarcloud:
#    needs: build
#    uses: ZayraGS1403/central-pipelines/.github/workflows/sonarcloud-analysis.yml@v0.1.1
#    with:
#      node-version: '20'
#      branch-name: ${{ github.ref_name }}
#    secrets:
#      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
#      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}