name: Deploy - Frontend EciBombit

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: docker build -t myregistry.azurecr.io/frontend .
      - run: echo "${{ secrets.ACR_PASSWORD }}" | docker login myregistry.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
      - run: docker push myregistry.azurecr.io/frontend

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name frontend \
            --resource-group bomberman-rg \
            --image myregistry.azurecr.io/frontend